"""initial schema

Revision ID: c70604414f16
Revises: 
Create Date: 2026-05-09 21:46:29.550183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70604414f16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('system_key', sa.String(length=50), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_table('classroom',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'duotopia', 'google_classroom')", name='ck_classroom_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_classroom_user_name')
    )
    op.create_index(op.f('ix_classroom_user_id'), 'classroom', ['user_id'], unique=False)
    op.create_table('semester',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('term IN (1, 2)', name='ck_semester_term'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'academic_year', 'term', name='uq_semester_year_term')
    )
    op.create_index('ix_semester_one_current_per_user', 'semester', ['user_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_index(op.f('ix_semester_user_id'), 'semester', ['user_id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_subject_user_name')
    )
    op.create_index(op.f('ix_subject_user_id'), 'subject', ['user_id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject_id', 'category_id', 'semester_id', 'name', name='uq_item_subject_category_semester_name')
    )
    op.create_index(op.f('ix_item_category_id'), 'item', ['category_id'], unique=False)
    op.create_index(op.f('ix_item_semester_id'), 'item', ['semester_id'], unique=False)
    op.create_index(op.f('ix_item_subject_id'), 'item', ['subject_id'], unique=False)
    op.create_index(op.f('ix_item_user_id'), 'item', ['user_id'], unique=False)
    op.create_table('point_rule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_awarded >= 0', name='ck_point_rule_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_point_rule_user_category')
    )
    op.create_index(op.f('ix_point_rule_category_id'), 'point_rule', ['category_id'], unique=False)
    op.create_index(op.f('ix_point_rule_user_id'), 'point_rule', ['user_id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'duotopia', 'google_classroom')", name='ck_student_source'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'classroom_id', 'seat_number', name='uq_student_user_classroom_seat')
    )
    op.create_index(op.f('ix_student_classroom_id'), 'student', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'duotopia', 'google_classroom')", name='ck_grade_source'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_grade_score_range'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'student_id', name='uq_grade_item_student')
    )
    op.create_index(op.f('ix_grade_item_id'), 'grade', ['item_id'], unique=False)
    op.create_index(op.f('ix_grade_student_id'), 'grade', ['student_id'], unique=False)
    op.create_index(op.f('ix_grade_user_id'), 'grade', ['user_id'], unique=False)
    op.create_table('item_classroom',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'classroom_id')
    )
    op.create_table('student_standard',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('threshold >= 0 AND threshold <= 100', name='ck_standard_threshold_range'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'category_id', name='uq_standard_student_category')
    )
    op.create_index(op.f('ix_student_standard_category_id'), 'student_standard', ['category_id'], unique=False)
    op.create_index(op.f('ix_student_standard_student_id'), 'student_standard', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_standard_user_id'), 'student_standard', ['user_id'], unique=False)
    op.create_table('point_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('source_grade_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_grade_id'], ['grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_grade_id')
    )
    op.create_index(op.f('ix_point_record_student_id'), 'point_record', ['student_id'], unique=False)
    op.create_index(op.f('ix_point_record_user_id'), 'point_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_record_user_id'), table_name='point_record')
    op.drop_index(op.f('ix_point_record_student_id'), table_name='point_record')
    op.drop_table('point_record')
    op.drop_index(op.f('ix_student_standard_user_id'), table_name='student_standard')
    op.drop_index(op.f('ix_student_standard_student_id'), table_name='student_standard')
    op.drop_index(op.f('ix_student_standard_category_id'), table_name='student_standard')
    op.drop_table('student_standard')
    op.drop_table('item_classroom')
    op.drop_index(op.f('ix_grade_user_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_student_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_item_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.drop_index(op.f('ix_student_classroom_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_point_rule_user_id'), table_name='point_rule')
    op.drop_index(op.f('ix_point_rule_category_id'), table_name='point_rule')
    op.drop_table('point_rule')
    op.drop_index(op.f('ix_item_user_id'), table_name='item')
    op.drop_index(op.f('ix_item_subject_id'), table_name='item')
    op.drop_index(op.f('ix_item_semester_id'), table_name='item')
    op.drop_index(op.f('ix_item_category_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_subject_user_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_semester_user_id'), table_name='semester')
    op.drop_index('ix_semester_one_current_per_user', table_name='semester', postgresql_where=sa.text('is_current = true'))
    op.drop_table('semester')
    op.drop_index(op.f('ix_classroom_user_id'), table_name='classroom')
    op.drop_table('classroom')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
