"""add student email and account_link

Revision ID: e005b3d6ddb6
Revises: c70604414f16
Create Date: 2026-05-09 22:26:22.978543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e005b3d6ddb6'
down_revision: Union[str, Sequence[str], None] = 'c70604414f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('link_role', sa.String(length=32), nullable=False),
    sa.Column('linked_via', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_role IN ('self', 'parent')", name='ck_account_link_role'),
    sa.CheckConstraint("linked_via IN ('email_invite', 'manual', 'invite_code')", name='ck_account_link_linked_via'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'auth_user_id', 'link_role', name='uq_account_link_student_user_role')
    )
    op.create_index(op.f('ix_account_link_auth_user_id'), 'account_link', ['auth_user_id'], unique=False)
    op.create_index('ix_account_link_one_self_per_student', 'account_link', ['student_id'], unique=True, postgresql_where=sa.text("link_role = 'self'"))
    op.create_index(op.f('ix_account_link_student_id'), 'account_link', ['student_id'], unique=False)
    op.add_column('student', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_column('student', 'email')
    op.drop_index(op.f('ix_account_link_student_id'), table_name='account_link')
    op.drop_index('ix_account_link_one_self_per_student', table_name='account_link', postgresql_where=sa.text("link_role = 'self'"))
    op.drop_index(op.f('ix_account_link_auth_user_id'), table_name='account_link')
    op.drop_table('account_link')
    # ### end Alembic commands ###
